hubble_site/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('leds/', include('leds.urls')),
    path('admin/', admin.site.urls),
]

leds/urls.py
from django.urls import path

from . import views


app_name = 'leds'
urlpatterns = [ 
    path('', views.index, name='index'),
    path('colors/', views.all_colors, name='all_colors'),
    path('boards/', views.all_boards, name='all_boards'),

    path('colors/<color_name>/', views.color, name='color'),
    path('boards/<board_label>/', views.board, name='board'),

    path('LED_click/<int:led_index>/', views.LED_click, name='LED_click'),
    path('colorClick/<color_label>/', views.color_click, name='color_click'),
    path('boardClick/<board_label>/', views.board_click, name='board_click')
]

leds/models.py
from django.db import models
from django.core import serializers




class Color(models.Model):
    label = models.CharField(default="no_label", max_length=20)
    r = models.PositiveSmallIntegerField(default=0)
    g = models.PositiveSmallIntegerField(default=0)
    b = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        return self.label + " (" \
            + str(self.r) + "," + str(self.g) \
            + "," + str(self.b) + ")"

    def json(self):
        dat = serializers.serialize("json", [self])
        return dat


class Board(models.Model):
    height = models.PositiveSmallIntegerField(default=8)
    width = models.PositiveSmallIntegerField(default=32)
    label = models.CharField(default="board", max_length=30)

    # one to many leds

    def __str__(self):
        return self.label
        
    # display array of leds
    def display_arr(self):
        ret = []
        for y in range(self.height):
            row = []
            for x in range(self.width):
                idx = x * self.height + y
                led = LED.objects.get(board=self, index=idx)
                row.append(led)
            ret.append(row)
        return ret

    def json(self):
        dat = serializers.serialize("json", [self])
        return dat

    def size(self):
        return self.width * self.height      

    def divisible_by_height(self, num):
        return num % self.height == 0

    #def led(self, idx):
        #return self.leds[idx]


class LED(models.Model):
    index = models.IntegerField(default=0)
    color = models.ForeignKey(Color, on_delete=models.CASCADE)
    board = models.ForeignKey(Board, on_delete=models.CASCADE, default='')

    def __str__(self):
        return self.board.label + ":" + str(self.index)

    class Meta:
        constraints = [
            # index >= 0
            models.CheckConstraint(
                check = models.Q(index__gte=0),
                name = 'leds_LED_index_gte_0'
            )
            # no duplicate index for board
        ]

    def json(self):
        dat = serializers.serialize("json", [self])
        return dat

    def color_style(self):
        return "--color: " + self.color.label + ";"

leds/views.py
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect

import json

from .models import Color, Board, LED


def index(request):
    """Homepage"""

    all_colors = Color.objects.all() # change to selected colors
    all_boards = Board.objects.all() # change to selected boards

    try:
        current_color_label = request.session['current_color']
    except:
        current_color_label = None

    try:
        current_board_label = request.session['current_board']
        current_board = Board.objects.get(label=current_board_label)
        current_arr = current_board.display_arr()
    except:
        current_board = None
        current_arr = None

    context = { 
        'current_arr': current_arr,
        'colors': all_colors,
        'boards': all_boards,
        'current_color': current_color_label,
        'current_board': current_board
     }
    return render(request, 'leds/index.html', context)

def color(request, color_name):
    """Displays information for a given color"""
    color = get_object_or_404(Color, label=color_name)
    context = {
        'color': color
    }
    return render(request, 'leds/color.html', context)

def board(request, board_label):
    """Displays information for a given board"""
    board = get_object_or_404(Board, label=board_label)
    arr = board.display_arr()
    context = { 'board': board, 'arr': arr }
    return render(request, 'leds/board.html', context)

def all_colors(request):
    """Show all the colors"""
    all_colors = Color.objects.all()    
    context = {
        'all_colors': all_colors
    }
    return render(request, 'leds/all_colors.html', context)

def all_boards(request):
    """Show all boards"""
    all_boards = Board.objects.all()
    context = { 'all_boards': all_boards }
    return render(request, 'leds/all_boards.html', context)

def set_led_color(request, board_label, led_idx, color_label):

    board = Board.objects.get(label=board_label)
    led = board.leds[led_idx]
    color = Color.objects.get(label=color_label)

    led.color = color
    led.save()

    return HttpResponseRedirect(reverse('leds:boards', args=(board_label,)))


# session testing

def selected_color(request):
    """Get selected color from session"""
    _label = request.session['current_color']
    color = None if _label == 'none' else Color.objects.get(label=_label)
    return color


def LED_click(request, led_index):
    """An LED in a board is clicked
        set LED color"""
    # get selected color
    # find associated color by label
    color = selected_color(request)
    # get currently displayed board in session
    try:
        board_label = request.session['current_board']
        board = Board.objects.get(label=board_label)
    except:
        board = None
        
    if color is not None and board is not None:
        # find LED associated to button (by idx)
        #   and board
        led = LED.objects.get(index=led_index, board=board)
        # set LED color to color
        led.color = color
        # save
        led.save()

        print('set ', led_index, ' to ', color)

    # return to original page   
    return HttpResponseRedirect(reverse('leds:index'))

def color_click(request, color_label):
    """A displayed color is clicked
        select color"""
    color = Color.objects.get(label=color_label)
    obj = json.loads(color.json())[0]
    label = obj.get('fields').get('label')

    if not 'current_color' in request.session:
        request.session['current_color'] = 'none'
    elif request.session['current_color'] == label:
        request.session['current_color'] = 'none'
    else:
        request.session['current_color'] = label

    # return HttpResponse(request.session['current_color'])
    return HttpResponseRedirect(reverse('leds:index'))

def board_click(request, board_label):
    """A displayed board is clicked
        select board"""
    board = Board.objects.get(label=board_label)
    obj = json.loads(board.json())[0]
    label = obj.get('fields').get('label')

    if not 'current_board' in request.session:
        request.session['current_board'] = 'none'
    elif request.session['current_board'] == label:     
        request.session['current_board'] = 'none'
    else:
        request.session['current_board'] = label

    #return HttpResponse(request.session['current_board'])
    return HttpResponseRedirect(reverse('leds:index'))

leds/templates/leds/all_boards.html
<h3>All Boards:</h3>

{% for board in all_boards %}
    <a href="{% url 'leds:board' board.label %}">
        {{ board.label }}
    </a>
{% endfor %}

leds/templates/leds/all_colors.html
{% if all_colors %}

<h3>All Colors:</h3>

{% for color in all_colors %}
    <a href="{% url 'leds:color' color.label %}">{{ color.label }}</a>
    <br>
{% endfor %}

{% endif %}

leds/templates/leds/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'leds/style.css' %}">
    <script src="{% static 'leds/funcs.js' %}"></script>
</head>
<body>
    {% block body %}{% endblock %}
</body>

leds/templates/leds/board.html
<h3>Board: {{ board.label }}</h3>
<p>Size: {{ board.size }}</p>
<p>Dimensions: {{ board.width }} x {{ board.height }}</p>

{% for col in arr %}
    {% for led in col %}
    <form class='led' action='LED_click/{{ led.index }}' method='GET'>
        <button class="led">{{ led.color }}</button>
    </form>
    {% endfor %}
    <br>
    <br>
{% endfor %}

leds/templates/leds/board_preview.html
<h3>Boards:</h3>
<p>Current Board: {{ current_board }}</p>
<a href='boards/'>View boards</a><br>
<br><br>

{% for board in boards %}
<form class='led' action='boardClick/{{ board.label }}/' method='GET'>
    <button class='board' type='submit'>{{ board.label }}</button>
</form>
{% endfor %}

leds/templates/leds/color.html
{% if color %}

<p>Color: {{ color.label }}</p>
<ul>
    <li>r: {{ color.r }}</li>
    <li>g: {{ color.g }}</li>
    <li>b: {{ color.b }}</li>
</ul>

{% endif %}

leds/templates/leds/color_preview.html
<h3>Colors:</h3>
<p>Current Color: {{ current_color }}</p>
<a href='colors/'>View colors</a><br>
<br>

{% for color in colors %}
<form class='led' action='colorClick/{{ color.label }}/' method='GET'>
    <button class='color' type='submit' onclick="changeCurrentColor(
        this, '{{ color.json }}')">{{ color.label }}</button>
</form>
{% endfor %}

leds/templates/leds/colors.html
<br>

<a href='colors/'>View colors</a>

<br>
<p>Colors:</p>
<p>Current Color: {{ current_color }}</p>
<br>

{% for color in colors %}
<form class='led' action='colorClick/{{ color.label }}/' method='GET'>
    <button class='color' type='submit' onclick="changeCurrentColor(
        this, '{{ color.json }}')">{{ color.label }}</button>
</form>
{% endfor %}
<br>

leds/templates/leds/index.html
{% extends "leds/base.html" %}
{% block body %}

    <p>LEDs index (html)</p>

    <br>
    {% block colors %}
        {% include "leds/color_preview.html" %}
    {% endblock %}
    <br>

    <br>
    {% block boards %}
        {% include "leds/board_preview.html" %}
    {% endblock %}
    <br>

    {% if current_board %}
    <br>
    {% block current_board_display %}
        {% with current_board as board and current_arr as arr %}
        {% include "leds/board.html" %}
        {% endwith %}
    {% endblock %}
    {% endif %}

{% endblock %}